// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgVfOpCNDy8XNMBKKREyCRyiHmXbocoeI',
    appId: '1:379627018712:web:3594c4ebf4e7ca89877aad',
    messagingSenderId: '379627018712',
    projectId: 'test-8b927',
    authDomain: 'test-8b927.firebaseapp.com',
    storageBucket: 'test-8b927.appspot.com',
    measurementId: 'G-Y6N45NQS07',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp5L8aGNoTiWqYnophBYxXAWfVhIjrqYE',
    appId: '1:379627018712:android:839d31ac420d2b95877aad',
    messagingSenderId: '379627018712',
    projectId: 'test-8b927',
    storageBucket: 'test-8b927.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDyol8CfCGPqmJv3l1qqwoD48ADo9NMG4o',
    appId: '1:379627018712:ios:661a34a0a691c872877aad',
    messagingSenderId: '379627018712',
    projectId: 'test-8b927',
    storageBucket: 'test-8b927.appspot.com',
    iosBundleId: 'com.example.firebaseTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDyol8CfCGPqmJv3l1qqwoD48ADo9NMG4o',
    appId: '1:379627018712:ios:a8adbc25e122909b877aad',
    messagingSenderId: '379627018712',
    projectId: 'test-8b927',
    storageBucket: 'test-8b927.appspot.com',
    iosBundleId: 'com.example.firebaseTest.RunnerTests',
  );
}
